title: Notes
author: Rahul Gill
description: Notes I made
google_analytics:
google_site_verification_content: 
disqus_forum_shortname: rahul-gill-github-io

show_thm_htb_badges_in_nav: false
github_username: rahul-gill
gitlab:
medium:
stackoverflow: users/15812773/rahul-gill
hacker_news:
linkedin: rahul-gill-466a1620a 
twitch:
youtube:
twitter: 
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : false

plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   notes:
      output: true
      permalink: /:collection/:categories/:name
   blogs:
      output: true
      permalink: /:collection/:year/:name