author: Rahul Gill
description: Notes I made

show_thm_htb_badges_in_nav: false
github_username: rahul-gill
gitlab:
medium:
stackoverflow: users/15812773/rahul-gill
hacker_news:
linkedin: rahul-gill-466a1620a 
twitch:
youtube:
twitter: 
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : false
   math_engine: nil

plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
   - jekyll-katex
collections:
   pages:
      output: true
      permalink: /:name
   notes:
      output: true
      permalink: /:collection/:categories/:name
   blogs:
      output: true
      permalink: /:collection/:year/:name

defaults:
   -  scope:
         path: /assets/images
      values:
         image: true
         permalink: /images/:name